/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ValidatorRouteImport } from './routes/validator'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as DeveloperGovernanceRouteImport } from './routes/developer.governance'
import { Route as DeveloperPromptsRouteImport } from './routes/developer.prompts'
import { Route as DeveloperResourcesRouteImport } from './routes/developer.resources'
import { Route as DeveloperSectorSpecificsRouteImport } from './routes/developer.sector-specifics'
import { Route as NewModelCompanyInformationRouteImport } from './routes/new-model.company-information'
import { Route as NewModelGenerateRouteImport } from './routes/new-model.generate'
import { Route as NewModelUploadRouteImport } from './routes/new-model.upload'
import { Route as RoleUserRouteImport } from './routes/role/user'
import { Route as DeveloperResourcesIndexRouteImport } from './routes/developer.resources.index'
import { Route as DeveloperResourcesGuidelinesRouteImport } from './routes/developer.resources.guidelines'
import { Route as DeveloperResourcesMarketDataRouteImport } from './routes/developer.resources.market-data'
import { Route as DeveloperResourcesTemplatesRouteImport } from './routes/developer.resources.templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorRoute = ValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperGovernanceRoute = DeveloperGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperPromptsRoute = DeveloperPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperResourcesRoute = DeveloperResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperSectorSpecificsRoute =
  DeveloperSectorSpecificsRouteImport.update({
    id: '/sector-specifics',
    path: '/sector-specifics',
    getParentRoute: () => DeveloperRoute,
  } as any)
const NewModelCompanyInformationRoute =
  NewModelCompanyInformationRouteImport.update({
    id: '/new-model/company-information',
    path: '/new-model/company-information',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewModelGenerateRoute = NewModelGenerateRouteImport.update({
  id: '/new-model/generate',
  path: '/new-model/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const NewModelUploadRoute = NewModelUploadRouteImport.update({
  id: '/new-model/upload',
  path: '/new-model/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleUserRoute = RoleUserRouteImport.update({
  id: '/role/user',
  path: '/role/user',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperResourcesIndexRoute = DeveloperResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeveloperResourcesRoute,
} as any)
const DeveloperResourcesGuidelinesRoute =
  DeveloperResourcesGuidelinesRouteImport.update({
    id: '/guidelines',
    path: '/guidelines',
    getParentRoute: () => DeveloperResourcesRoute,
  } as any)
const DeveloperResourcesMarketDataRoute =
  DeveloperResourcesMarketDataRouteImport.update({
    id: '/market-data',
    path: '/market-data',
    getParentRoute: () => DeveloperResourcesRoute,
  } as any)
const DeveloperResourcesTemplatesRoute =
  DeveloperResourcesTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => DeveloperResourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/guidelines': typeof GuidelinesRoute
  '/help': typeof HelpRoute
  '/validator': typeof ValidatorRoute
  '/api/chat': typeof ApiChatRoute
  '/developer/governance': typeof DeveloperGovernanceRoute
  '/developer/prompts': typeof DeveloperPromptsRoute
  '/developer/resources': typeof DeveloperResourcesRouteWithChildren
  '/developer/sector-specifics': typeof DeveloperSectorSpecificsRoute
  '/new-model/company-information': typeof NewModelCompanyInformationRoute
  '/new-model/generate': typeof NewModelGenerateRoute
  '/new-model/upload': typeof NewModelUploadRoute
  '/role/user': typeof RoleUserRoute
  '/developer/': typeof DeveloperIndexRoute
  '/developer/resources/guidelines': typeof DeveloperResourcesGuidelinesRoute
  '/developer/resources/market-data': typeof DeveloperResourcesMarketDataRoute
  '/developer/resources/templates': typeof DeveloperResourcesTemplatesRoute
  '/developer/resources/': typeof DeveloperResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/help': typeof HelpRoute
  '/validator': typeof ValidatorRoute
  '/api/chat': typeof ApiChatRoute
  '/developer/governance': typeof DeveloperGovernanceRoute
  '/developer/prompts': typeof DeveloperPromptsRoute
  '/developer/sector-specifics': typeof DeveloperSectorSpecificsRoute
  '/new-model/company-information': typeof NewModelCompanyInformationRoute
  '/new-model/generate': typeof NewModelGenerateRoute
  '/new-model/upload': typeof NewModelUploadRoute
  '/role/user': typeof RoleUserRoute
  '/developer': typeof DeveloperIndexRoute
  '/developer/resources/guidelines': typeof DeveloperResourcesGuidelinesRoute
  '/developer/resources/market-data': typeof DeveloperResourcesMarketDataRoute
  '/developer/resources/templates': typeof DeveloperResourcesTemplatesRoute
  '/developer/resources': typeof DeveloperResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/guidelines': typeof GuidelinesRoute
  '/help': typeof HelpRoute
  '/validator': typeof ValidatorRoute
  '/api/chat': typeof ApiChatRoute
  '/developer/governance': typeof DeveloperGovernanceRoute
  '/developer/prompts': typeof DeveloperPromptsRoute
  '/developer/resources': typeof DeveloperResourcesRouteWithChildren
  '/developer/sector-specifics': typeof DeveloperSectorSpecificsRoute
  '/new-model/company-information': typeof NewModelCompanyInformationRoute
  '/new-model/generate': typeof NewModelGenerateRoute
  '/new-model/upload': typeof NewModelUploadRoute
  '/role/user': typeof RoleUserRoute
  '/developer/': typeof DeveloperIndexRoute
  '/developer/resources/guidelines': typeof DeveloperResourcesGuidelinesRoute
  '/developer/resources/market-data': typeof DeveloperResourcesMarketDataRoute
  '/developer/resources/templates': typeof DeveloperResourcesTemplatesRoute
  '/developer/resources/': typeof DeveloperResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/developer'
    | '/guidelines'
    | '/help'
    | '/validator'
    | '/api/chat'
    | '/developer/governance'
    | '/developer/prompts'
    | '/developer/resources'
    | '/developer/sector-specifics'
    | '/new-model/company-information'
    | '/new-model/generate'
    | '/new-model/upload'
    | '/role/user'
    | '/developer/'
    | '/developer/resources/guidelines'
    | '/developer/resources/market-data'
    | '/developer/resources/templates'
    | '/developer/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/guidelines'
    | '/help'
    | '/validator'
    | '/api/chat'
    | '/developer/governance'
    | '/developer/prompts'
    | '/developer/sector-specifics'
    | '/new-model/company-information'
    | '/new-model/generate'
    | '/new-model/upload'
    | '/role/user'
    | '/developer'
    | '/developer/resources/guidelines'
    | '/developer/resources/market-data'
    | '/developer/resources/templates'
    | '/developer/resources'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/developer'
    | '/guidelines'
    | '/help'
    | '/validator'
    | '/api/chat'
    | '/developer/governance'
    | '/developer/prompts'
    | '/developer/resources'
    | '/developer/sector-specifics'
    | '/new-model/company-information'
    | '/new-model/generate'
    | '/new-model/upload'
    | '/role/user'
    | '/developer/'
    | '/developer/resources/guidelines'
    | '/developer/resources/market-data'
    | '/developer/resources/templates'
    | '/developer/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DeveloperRoute: typeof DeveloperRouteWithChildren
  GuidelinesRoute: typeof GuidelinesRoute
  HelpRoute: typeof HelpRoute
  ValidatorRoute: typeof ValidatorRoute
  ApiChatRoute: typeof ApiChatRoute
  NewModelCompanyInformationRoute: typeof NewModelCompanyInformationRoute
  NewModelGenerateRoute: typeof NewModelGenerateRoute
  NewModelUploadRoute: typeof NewModelUploadRoute
  RoleUserRoute: typeof RoleUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validator': {
      id: '/validator'
      path: '/validator'
      fullPath: '/validator'
      preLoaderRoute: typeof ValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/governance': {
      id: '/developer/governance'
      path: '/governance'
      fullPath: '/developer/governance'
      preLoaderRoute: typeof DeveloperGovernanceRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/prompts': {
      id: '/developer/prompts'
      path: '/prompts'
      fullPath: '/developer/prompts'
      preLoaderRoute: typeof DeveloperPromptsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/resources': {
      id: '/developer/resources'
      path: '/resources'
      fullPath: '/developer/resources'
      preLoaderRoute: typeof DeveloperResourcesRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/sector-specifics': {
      id: '/developer/sector-specifics'
      path: '/sector-specifics'
      fullPath: '/developer/sector-specifics'
      preLoaderRoute: typeof DeveloperSectorSpecificsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/new-model/company-information': {
      id: '/new-model/company-information'
      path: '/new-model/company-information'
      fullPath: '/new-model/company-information'
      preLoaderRoute: typeof NewModelCompanyInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-model/generate': {
      id: '/new-model/generate'
      path: '/new-model/generate'
      fullPath: '/new-model/generate'
      preLoaderRoute: typeof NewModelGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-model/upload': {
      id: '/new-model/upload'
      path: '/new-model/upload'
      fullPath: '/new-model/upload'
      preLoaderRoute: typeof NewModelUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role/user': {
      id: '/role/user'
      path: '/role/user'
      fullPath: '/role/user'
      preLoaderRoute: typeof RoleUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/resources/': {
      id: '/developer/resources/'
      path: '/'
      fullPath: '/developer/resources/'
      preLoaderRoute: typeof DeveloperResourcesIndexRouteImport
      parentRoute: typeof DeveloperResourcesRoute
    }
    '/developer/resources/guidelines': {
      id: '/developer/resources/guidelines'
      path: '/guidelines'
      fullPath: '/developer/resources/guidelines'
      preLoaderRoute: typeof DeveloperResourcesGuidelinesRouteImport
      parentRoute: typeof DeveloperResourcesRoute
    }
    '/developer/resources/market-data': {
      id: '/developer/resources/market-data'
      path: '/market-data'
      fullPath: '/developer/resources/market-data'
      preLoaderRoute: typeof DeveloperResourcesMarketDataRouteImport
      parentRoute: typeof DeveloperResourcesRoute
    }
    '/developer/resources/templates': {
      id: '/developer/resources/templates'
      path: '/templates'
      fullPath: '/developer/resources/templates'
      preLoaderRoute: typeof DeveloperResourcesTemplatesRouteImport
      parentRoute: typeof DeveloperResourcesRoute
    }
  }
}

interface DeveloperResourcesRouteChildren {
  DeveloperResourcesGuidelinesRoute: typeof DeveloperResourcesGuidelinesRoute
  DeveloperResourcesMarketDataRoute: typeof DeveloperResourcesMarketDataRoute
  DeveloperResourcesTemplatesRoute: typeof DeveloperResourcesTemplatesRoute
  DeveloperResourcesIndexRoute: typeof DeveloperResourcesIndexRoute
}

const DeveloperResourcesRouteChildren: DeveloperResourcesRouteChildren = {
  DeveloperResourcesGuidelinesRoute: DeveloperResourcesGuidelinesRoute,
  DeveloperResourcesMarketDataRoute: DeveloperResourcesMarketDataRoute,
  DeveloperResourcesTemplatesRoute: DeveloperResourcesTemplatesRoute,
  DeveloperResourcesIndexRoute: DeveloperResourcesIndexRoute,
}

const DeveloperResourcesRouteWithChildren =
  DeveloperResourcesRoute._addFileChildren(DeveloperResourcesRouteChildren)

interface DeveloperRouteChildren {
  DeveloperGovernanceRoute: typeof DeveloperGovernanceRoute
  DeveloperPromptsRoute: typeof DeveloperPromptsRoute
  DeveloperResourcesRoute: typeof DeveloperResourcesRouteWithChildren
  DeveloperSectorSpecificsRoute: typeof DeveloperSectorSpecificsRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperGovernanceRoute: DeveloperGovernanceRoute,
  DeveloperPromptsRoute: DeveloperPromptsRoute,
  DeveloperResourcesRoute: DeveloperResourcesRouteWithChildren,
  DeveloperSectorSpecificsRoute: DeveloperSectorSpecificsRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DeveloperRoute: DeveloperRouteWithChildren,
  GuidelinesRoute: GuidelinesRoute,
  HelpRoute: HelpRoute,
  ValidatorRoute: ValidatorRoute,
  ApiChatRoute: ApiChatRoute,
  NewModelCompanyInformationRoute: NewModelCompanyInformationRoute,
  NewModelGenerateRoute: NewModelGenerateRoute,
  NewModelUploadRoute: NewModelUploadRoute,
  RoleUserRoute: RoleUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
